version = 1

[plugins]
osv-scanner = true        # Enable dependency vulnerability scanning
eslint = true             # Optional: enable linting for JavaScript

[osv-scanner]
fail_severity = "high"    # Fail pipeline only on high/critical vulnerabilities

[general]
exclude = ["node_modules/**"]
