version = 1

[general]
exclude = ["node_modules/**", "coverage/**", "dist/**"]

[plugins]
osv-scanner = true
eslint = true
prettier = true
duplication = true
coverage = true

[osv-scanner]
fail_severity = "medium"

[eslint]
paths = ["lib/**/*.js", "index.js"]
config = ".eslintrc.json"

[prettier]
config = ".prettierrc"

[duplication]
paths = ["lib/**/*.js", "index.js"]
min_lines = 5

[coverage]
line = 80
branch = 70
function = 70
statement = 75
